{"name": "Verifying the list of blogs when the Blog posts End point is triggered", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /api/blog/posts/?page=1&bool=true&per_page=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD21A4F40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\blog_posts_steps.py\", line 21, in submit_get\n    response = requests.get(app_url[0], params=app_url[1])\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\sessions.py\", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\sessions.py\", line 645, in send\n    r = adapter.send(request, **kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "steps": [{"name": "Given I want to retrieve list of posts when blog posts end point is triggered", "status": "passed", "start": 1647256339679, "stop": 1647256339679}, {"name": "When I submit Get request with query parameters", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /api/blog/posts/?page=1&bool=true&per_page=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD21A4F40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\blog_posts_steps.py\", line 21, in submit_get\n    response = requests.get(app_url[0], params=app_url[1])\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\sessions.py\", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\sessions.py\", line 645, in send\n    r = adapter.send(request, **kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\lumira-dx_apitesting_behave\\venv\\lib\\site-packages\\requests\\adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1647256339680, "stop": 1647256343786}, {"name": "Then the response is success and validating the get posts response schema", "status": "skipped", "start": 1647256343790, "stop": 1647256343790}, {"name": "And validating the items field for the post", "status": "skipped", "start": 1647256343790, "stop": 1647256343790}], "start": 1647256339678, "stop": 1647256343790, "uuid": "ca545327-f105-4287-a411-67019daa1557", "historyId": "fde5e2850de1638053cdf44f8c9234a7", "fullName": "Operations related to Blog posts: Verifying the list of blogs when the Blog posts End point is triggered", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Operations related to Blog posts"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}